### ISSUE TITLE
refactor passwords file

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/signingscript#68]
It would be nice to specify defaults, rather than duplicating info on every line.
Something like

```yaml
projects:releng:blah
    signing-server:
          urls:
              - https://signing-1
          formats: ['gpg', ...]
          user: ...
          pass: ...
          server-type: signing-server
    autograph:
projects:releng:blah2:
    ...
```
